apiVersion: v1
kind: Service
metadata:
  name: {{ include "egernia.fullname" . }}-tap-api
  labels:
    {{- include "egernia.labels" . | nindent 4 }}
    app.kubernetes.io/component: tap-api
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: tap-api
  ports:
    - name: http
      port: {{ .Values.tapApi.port }}
      targetPort: http
