apiVersion: v1
kind: Secret
metadata:
  name: {{ include "egernia.fullname" . }}-db
  labels:
    {{- include "egernia.labels" . | nindent 4 }}
type: Opaque
stringData:
  TAP_DATABASE_URL: {{ include "egernia.databaseUrl" . | quote }}
  {{- if .Values.postgresql.enabled }}
  POSTGRES_USER: {{ .Values.postgresql.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | quote }}
  POSTGRES_DB: {{ .Values.postgresql.database | quote }}
  {{- end }}
