apiVersion: v1
kind: Service
metadata:
  name: {{ include "egernia.fullname" . }}-tap-api
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "egernia.labels" . | nindent 4 }}
    app.kubernetes.io/component: tap-api
spec:
  type: {{ .Values.tapApi.service.type }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: tap-api
  ports:
    - name: http
      port: {{ .Values.tapApi.port }}
      targetPort: http
      {{- if and (eq .Values.tapApi.service.type "NodePort") .Values.tapApi.service.nodePort }}
      nodePort: {{ .Values.tapApi.service.nodePort }}
      {{- end }}
