version: 2
updates:
  - package-ecosystem: uv
    directory: "/"
    schedule:
      interval: weekly
    groups:
      python-dependencies:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      codeql:
        patterns: ["github/codeql-action*"]
  - package-ecosystem: docker
    directories:
      - "/services/egernia-api"
      - "/services/egernia-executor"
      - "/db"
    schedule:
      interval: weekly
