apiVersion: v1
kind: Service
metadata:
  name: {{ include "skao-tap.fullname" . }}-tap-api
  labels:
    {{- include "skao-tap.labels" . | nindent 4 }}
    app.kubernetes.io/component: tap-api
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: tap-api
  ports:
    - name: http
      port: {{ .Values.tapApi.port }}
      targetPort: http
