apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "skao-tap.fullname" . }}-config
  labels:
    {{- include "skao-tap.labels" . | nindent 4 }}
data:
  TAP_BASE_URL: {{ include "skao-tap.baseUrl" . | quote }}
  TAP_RESULTS_DIR: /results
  TAP_QUERY_ROLE: {{ .Values.config.queryRole | quote }}
  {{- /* int64 guards against Helm rendering large numbers as 1e+06 */}}
  TAP_DEFAULT_MAXREC: {{ .Values.config.defaultMaxrec | int64 | quote }}
  TAP_HARD_MAXREC: {{ .Values.config.hardMaxrec | int64 | quote }}
  TAP_SYNC_TIMEOUT: {{ .Values.config.syncTimeoutSeconds | int64 | quote }}
  TAP_ASYNC_EXEC_DURATION: {{ .Values.config.asyncExecDurationSeconds | int64 | quote }}
  TAP_JOB_RETENTION: {{ .Values.config.jobRetentionSeconds | int64 | quote }}
  TAP_WAIT_MAX: {{ .Values.config.waitMaxSeconds | int64 | quote }}
  TAP_MODEL_PLUGINS: {{ .Values.config.modelPlugins | quote }}
  TAP_LOG_LEVEL: {{ .Values.config.logLevel | quote }}
