"""Generate the model-backed table reference used by the MkDocs site.

MkDocs loads this file as a hook, so every local and CI documentation build
reflects the versions of the data-model packages installed in that build.
It can also be run directly when the checked-in page needs refreshing.
"""

from collections.abc import Iterable
from pathlib import Path

from tapcore.metadata.plugins import MetadataPlugin, discovered_plugins
from tapcore.metadata.schema_gen import TAP_DATATYPES

OUTPUT_PATH = Path(__file__).resolve().parents[1] / "docs" / "model-schemas.md"


def _cell(value: object) -> str:
    """Render a value safely inside a Markdown table cell."""
    if value is None or value == "":
        return "—"
    return str(value).replace("|", "\\|").replace("\n", " ")


def render_schema_docs(plugins: Iterable[MetadataPlugin]) -> str:
    """Return the Markdown table reference for ``plugins``."""
    plugins = sorted(plugins, key=lambda plugin: plugin.name)
    lines = [
        "# Generated model schemas",
        "",
        "<!-- Generated by scripts/generate_model_schema_docs.py; do not edit by hand. -->",
        "",
        "This page is generated from the installed pydantic data models during every ",
        "MkDocs build. It therefore documents the same table and column definitions that ",
        "the service creates and registers in `TAP_SCHEMA` at startup.",
        "",
    ]

    for plugin in plugins:
        model_name = f"{plugin.model.__module__}.{plugin.model.__name__}"
        lines.extend(
            [
                f"## `{plugin.name}`",
                "",
                f"**Root model:** `{model_name}`  ",
                f"**SQL schema:** `{plugin.sql_schema}`  ",
                f"**JSON ingest endpoint:** `/api/v1/{plugin.mount}`",
                "",
            ]
        )
        for table in plugin.tables:
            lines.extend(
                [
                    f"### `{table.qualified}`",
                    "",
                    f"Model: `{table.model.__module__}.{table.model.__name__}`  ",
                    f"Primary key: `{', '.join(table.pk_columns)}`",
                    "",
                    "| Column | Model field | SQL type | TAP type | Nullable | Key | "
                    + "Constraints | Description |",
                    "|---|---|---|---|:---:|:---:|---|---|",
                ]
            )
            for column in table.columns:
                tap_type, arraysize = TAP_DATATYPES[column.sql_type]
                if arraysize:
                    tap_type = f"{tap_type}[{arraysize}]"
                model_field = (
                    f"derived from {column.derived_from}"
                    if column.derived_from
                    else ".".join(column.path)
                )
                constraints = "; ".join(column.checks)
                lines.append(
                    "| "
                    + " | ".join(
                        [
                            f"`{_cell(column.name)}`",
                            f"`{_cell(model_field)}`",
                            f"`{_cell(column.sql_type)}`",
                            f"`{_cell(tap_type)}`",
                            "yes" if column.nullable else "no",
                            "yes" if column.is_key else "no",
                            _cell(constraints),
                            _cell(column.description),
                        ]
                    )
                    + " |"
                )
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def render_installed_schema_docs() -> str:
    """Render every metadata plugin installed in the current environment."""
    return render_schema_docs(discovered_plugins().values())


def generate(output_path: Path = OUTPUT_PATH) -> Path:
    """Generate the page from every installed metadata plugin."""
    content = render_installed_schema_docs()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    return output_path


def on_config(config, **kwargs):
    """MkDocs hook: refresh model schemas before documentation files are read."""
    generate()
    return config


if __name__ == "__main__":
    print(generate())
